Trying to make it compile on Linux
It almost compiles on Manjaro Linux.

    Projucer --resave admv.jucer
    cd Builds/Linux/
    make CONFIG=Release

The old Visual Studio target is not supported anymore by JUCE and was
automatically removed by `Projucer`.

This code almost compiles, but it fails with this message:

```
In file included from ../../Source/GoniometerControl.h:5,
                 from ../../Source/PluginEditor.h:20:
../../Source/TomatlImageType.h:22:34: error: conflicting return type specified for ‘virtual juce::LowLevelGraphicsContext* TomatlPixelData::createLowLevelContext()’
   22 |         LowLevelGraphicsContext* createLowLevelContext() override
      |                                  ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/share/juce/modules/juce_graphics/juce_graphics.h:142,
                 from /usr/share/juce/modules/juce_audio_devices/juce_audio_devices.h:60,
                 from ../../Source/../JuceLibraryCode/JuceHeader.h:18:
/usr/share/juce/modules/juce_graphics/images/juce_Image.h:454:54: note: overridden function is ‘virtual std::unique_ptr<juce::LowLevelGraphicsContext> juce::ImagePixelData::createLowLevelContext()’
  454 |     virtual std::unique_ptr<LowLevelGraphicsContext> createLowLevelContext() = 0;
      |                                                      ^~~~~~~~~~~~~~~~~~~~~
../../Source/TomatlImageType.h:46:20: error: conflicting return type specified for ‘virtual juce::ImageType* TomatlPixelData::createType() const’
   46 |         ImageType* createType() const override    { return new SoftwareImageType(); }
      |                    ^~~~~~~~~~
/usr/share/juce/modules/juce_graphics/images/juce_Image.h:458:40: note: overridden function is ‘virtual std::unique_ptr<juce::ImageType> juce::ImagePixelData::createType() const’
  458 |     virtual std::unique_ptr<ImageType> createType() const = 0;
      |                                        ^~~~~~~~~~
```

I'm having trouble fixing this specific error, probably because I'm
already tired of trying to compile many projects.